name: Deploy All API Clients to Maven Central

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Import GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode | gpg --batch --import
          mkdir -p ~/.gnupg
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          gpg --list-secret-keys --keyid-format LONG
        shell: bash
      - name: Build and Deploy All Clients
        run: mvn release:clean release:prepare
      - name: Release
        uses: qcastel/github-actions-maven-release@master
        with:
          release-branch-name: "main"
          gpg-enabled: "true"
          gpg-key-id: ${{ secrets.GITHUB_GPG_KEY_ID }}
          gpg-key: ${{ secrets.GITHUB_GPG_KEY }}

          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@example.com"

          access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
